---
title: "Cartoon Figures"
author: "Zach"
date: 2018-08-29
output:
  github_document:
    toc: true
---

```{r setup, message=FALSE, warning=FALSE}
library(tidyverse)

## Script parameters ---------------------------------------------------
ext <- ".eps"
asp_ratio <- 4 / 4
img_width <- 5
img_height <- img_width * asp_ratio

## Helper functions ----------------------------------------------------
base_breaks <- function(n = 10){
    function(x) {
        axisTicks(log10(range(x, na.rm = TRUE)), log = TRUE, n = n)
    }
}

## Custom save function
mysave <- function(name) {
    ggsave(
        filename = str_c("../slides/images/", name, ext),
        height = img_height,
        width = img_width,
        units = "in"
    )
}
## Common theme settings
theme_common <- function() {
  theme_minimal() %+replace%
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_text(margin = margin(4, 4, 4, 4), size = 16),
    axis.title.y = element_text(margin = margin(4, 4, 4, 4), size = 16, angle = 90),

    aspect.ratio = 1 / 1,

    plot.margin   = unit(c(t = +0, b = +0, r = +0, l = +0), "cm"),
    panel.spacing = unit(c(t = +0, b = +0, r = +0, l = +0), "cm"),

    legend.text = element_text(size = 10),

    panel.grid.major = element_line(color = "grey90"),
    panel.grid.minor = element_line(color = "grey90")
  )
}
```

## Exponential growth
<!-- -------------------------------------------------- -->

```{r dimensionality}
df_comment <-
    tribble(
        ~time, ~comment,
        1.0e+0,  "One second",
        8.6e+5,  "One Day",
        1.0e+10, "Eleven generations",
        4.3e+17, "Age of Universe",
        1.0e+20, "230 x AoU"
    )

df_dim <-
    tibble(dimension = c(1, 20)) %>%
    mutate(time = 10 ^ dimension)

df_dim %>%
    ggplot(aes(y = time)) +
    geom_hline(
        data = df_comment,
        aes(yintercept = time),
        linetype = 2,
        color = "grey70"
    ) +
    geom_text(
        data = df_comment,
        aes(x = 1, label = comment),
        nudge_y = 1.0,
        hjust = 0
    ) +
    geom_line(aes(x = dimension)) +
    scale_x_continuous(trans = scales::log_trans(), breaks = base_breaks()) +
    scale_y_continuous(
        trans = scales::log_trans(),
        breaks = c(1e1, 1e10, 1e20)
    ) +
    theme_common() +
    labs(
        x = "Dimension",
        y = "Compute Time (Seconds)"
    )

mysave("dimensionality")
```

## Hypercubes
<!-- -------------------------------------------------- -->

```{r hypercubes}

```

## Surface Area Distribution
<!-- -------------------------------------------------- -->

```{r sa_dist}
dim_seq <- c(1, 2, 3, 5, 10, 50)
R_seq <- seq(0, 1, length = 100)

df_surf <-
    map_dfr(
        dim_seq,
        function(d) {tibble(
                         d = d,
                         rho = R_seq ^ (d - 1),
                         r = R_seq
                     )}
    )

df_surf %>%
    ggplot(aes(r, rho, color = as.factor(d))) +
    geom_line() +
    scale_x_continuous(breaks = c(0, 1/2, 1)) +
    scale_color_discrete(name = "Dimension") +
    theme_common() +
    labs(
        x = "Radial Position",
        y = "Surface Density"
    )

mysave("surface_density")
```

## Distance and Projection
<!-- -------------------------------------------------- -->

```{r proj_example}
df_proj <-
    tribble(
        ~x, ~y, ~proj,
        +1, +3, 0L,
        +1, +0, 1L,
        +2, +2, 2L,
        -2, -2, 2L,
        -1, -0, 1L,
        -1, -3, 0L
    )
```

```{r proj0}
## Base plot
df_proj %>%
    filter(proj == 0) %>%
    ggplot(aes(x, y)) +
    geom_point(size = 4) +
    geom_segment(
        aes(xend = lag(x), yend = lag(y)),
        size = 1.5
    ) +
    scale_x_continuous(
        limits = c(-3, +3)
    ) +
    scale_y_continuous(
        limits = c(-3, +3)
    ) +
    theme_common()

mysave("proj0")
```

```{r proj1}
## First projection
df_proj %>%
    filter(proj != 2) %>%
    ggplot(aes(x, y)) +
    geom_point(size = 4) +
    geom_abline(slope = 0, intercept = 0, linetype = 2) +
    geom_segment(
        data = df_proj %>% filter(proj != 2, x > 0),
        mapping = aes(xend = lag(x), yend = lag(y)),
        linetype = 3
    ) +
    geom_segment(
        data = df_proj %>% filter(proj != 2, x < 0),
        mapping = aes(xend = lag(x), yend = lag(y)),
        linetype = 3
    ) +
    geom_segment(
        data = df_proj %>% filter(proj == 1),
        mapping = aes(xend = lag(x), yend = lag(y)),
        linetype = 1,
        size = 1.5
    ) +
    scale_x_continuous(
        limits = c(-3, +3)
    ) +
    scale_y_continuous(
        limits = c(-3, +3)
    ) +
    theme_common()

mysave("proj1")
```

```{r proj2}
## First projection
df_proj %>%
    filter(proj != 1) %>%
    ggplot(aes(x, y)) +
    geom_point(size = 4) +
    geom_abline(slope = 1, intercept = 0, linetype = 2) +
    geom_segment(
        data = df_proj %>% filter(proj != 1, x > 0),
        mapping = aes(xend = lag(x), yend = lag(y)),
        linetype = 3
    ) +
    geom_segment(
        data = df_proj %>% filter(proj != 1, x < 0),
        mapping = aes(xend = lag(x), yend = lag(y)),
        linetype = 3
    ) +
    geom_segment(
        data = df_proj %>% filter(proj == 2),
        mapping = aes(xend = lag(x), yend = lag(y)),
        linetype = 1,
        size = 1.5
    ) +
    scale_x_continuous(
        limits = c(-3, +3)
    ) +
    scale_y_continuous(
        limits = c(-3, +3)
    ) +
    theme_common()

mysave("proj2")
```
